/*-----------------------------------------------------------------------------
 * File      - mainwindow.cpp
 * Author    - LEVAX
 * Purpose   - Handles GUI interaction and element data retrieval
 *---------------------------------------------------------------------------*/

#include "mainwindow.h"
#include "ui_mainwindow.h"

/* Constructor */
MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    ui->humanTotalSpinBox->setMaximum(MAX_PEOPLE);
    ui->humanVisitorSpinBox->setMaximum(MAX_VISITOR);

    /* Help menu listener */
    connect(ui->actionHelp, SIGNAL(triggered()), this, SLOT(onActionHelp()));

    /* Debug menu listener */
    connect(ui->actionCheckObj, SIGNAL(triggered()), this, SLOT(onActionCheckObj()));
}

/* Destructor */
MainWindow::~MainWindow()
{
    delete ui;
}

/* humanXMLUploadBtn dialog function */
void MainWindow::on_humanXMLUploadBtn_clicked()
{
    if(ui->buildingDirLabel->text() != "...")
    {
        /* Prompt dialog at current folder, accepting .xml file only */
        QFileDialog dlg(NULL, tr("Open Simulated Human Data"));
        dlg.setNameFilter(tr("XML Data File (*.xml)"));
        QString filename;

        /* Retrieve previous filename */
        QString prevFilename = ui->humanDirLabel->text();

        /* Check for Open button pressed */
        if(dlg.exec())
        {
            /* Get directory */
            filename = dlg.selectedFiles().at(0);

            /* Reset all previously loaded simulated human data */
            if((shh.getNumberOfSimulatedHumanObject() > 0 && prevFilename != "...") || (shh.getNumberOfVisitorObj() > 0 && prevFilename != "...")
               || (ui->humanTotalSpinBox->value() > 0 && prevFilename == "...") || (ui->humanVisitorSpinBox->value() > 0 && prevFilename == "..."))
            {
                /* Undo twice if data is already generated by spin boxes*/
                if(((ui->humanTotalSpinBox->value() > 0 && prevFilename == "...") && (ui->humanVisitorSpinBox->value() > 0 && prevFilename == "..."))
                   || ((shh.getNumberOfSimulatedHumanObject() > 0 && prevFilename != "...") && (shh.getNumberOfVisitorObj() >0 && prevFilename != "...")))
                {
                    ui->inputSummaryBox->undo();
                    ui->inputSummaryBox->undo();
                }
                else
                {
                    ui->inputSummaryBox->undo();
                }

                shh.resetAll();

                ui->humanTotalSpinBox->setValue(0);
                ui->humanAvgSpinBox->setValue(0);
                ui->humanVisitorSpinBox->setValue(0);
                ui->humanDirLabel->setDisabled(false);


            }

            /* Validate data */
            bool verify = validateHumanData(filename);

            /* Check if human data is invalid */
            if(!verify)
            {
                ui->humanDirLabel->setText("...");

                /* remove all data */
                shh.resetAll();

                /* Display error */
                QMessageBox::critical(this,tr("Error!"),"The XML file selected has errors in them<br>See Help to learn more about XML structures");
            }
            else
            {
                /* Display resident */
                if(shh.getNumberOfSimulatedHumanObject() > 0)
                    updateSummary(true);
                /* Display visitor */
                if(shh.getNumberOfVisitorObj() > 0)
                    updateSummary(false);

                /* Enable simulated human elements */
                ui->humanTotalSpinBox->setValue(0);
                ui->humanAvgSpinBox->setValue(0);
                ui->humanVisitorSpinBox->setValue(0);
                ui->humanDirLabel->setDisabled(false);
                ui->humanDirLabel->setText(filename);

            }
        }
    }
    else
    {
        /* Display warning message to load building XML first */
        QMessageBox::information(this,tr("Notice"), "Please load building XML first");
    }
}

/* buildingXMLUploadBtn dialog function */
void MainWindow::on_buildingXMLUploadBtn_clicked()
{
    /* Prompt dialog at current folder, accepting .xml file only */
    QFileDialog dlg(NULL, tr("Open Building Model"));
    dlg.setNameFilter(tr("XML Data File (*.xml)"));
    QString filename;

    /* Check for Open button pressed */
    if(dlg.exec())
    {
        /* Get directory */
        filename = dlg.selectedFiles().at(0);

        /* Clear inputSummaryBox */
        ui->inputSummaryBox->clear();

        /* Reset all lift data before any input */
        lh.resetAll();
        /* Reset all simulated human data before any input */
        shh.resetAll();


        /* Validate data */
        QString summary = validateBuildingData(filename);

        /* Check if building data is invalid */
        if(summary == "false")
        {
            /* Reset all elements */
            ui->buildingDirLabel->setText("...");
            ui->humanDirLabel->setText("...");
            ui->humanDirLabel->setDisabled(true);
            ui->humanTotalSpinBox->setDisabled(true);
            ui->humanAvgSpinBox->setDisabled(true);
            ui->humanVisitorSpinBox->setDisabled(true);
            ui->humanTotalSpinBox->setValue(0);
            ui->humanAvgSpinBox->setValue(0);
            ui->humanVisitorSpinBox->setValue(0);

            /* reset all building due to error */
            bh.resetAll();

            /* Display error */
            QMessageBox::critical(this,tr("Error!"),"The XML file selected has errors in them<br>See Help to learn more about XML structures");
        }
        else
        {
            /* Display to inputSummaryBox */
            ui->inputSummaryBox->append(summary);

            /* Set elements to enable */
            ui->buildingDirLabel->setText(filename);
            ui->humanDirLabel->setDisabled(false);
            ui->humanTotalSpinBox->setDisabled(false);
            //ui->humanAvgSpinBox->setDisabled(false);
            ui->humanVisitorSpinBox->setDisabled(false);
            ui->humanDirLabel->setText("...");
            ui->humanTotalSpinBox->setValue(0);
            ui->humanAvgSpinBox->setValue(0);
            ui->humanVisitorSpinBox->setValue(0);
        }
    }
}

/* Handle total human spin box value changed */
void MainWindow::on_humanTotalSpinBox_valueChanged(int arg1)
{
    /* Set average floor value */
    int avgPerFloor = arg1/bh.getNoOfFloor();
    ui->humanAvgSpinBox->setValue(avgPerFloor);

    /* Get previous human file name and previous human label enabled status */
    bool prevHumanLabelStatus = ui->humanDirLabel->isEnabled();
    QString prevFilename = ui->humanDirLabel->text();

    bool update = false;

    /* Only update when value is more than or equal to 0 */
    if(arg1 >= 0)
    {
        /* Undo and clear memory if previous data is loaded */
        if(prevHumanLabelStatus == true && prevFilename != "...")
        {
            /* Two types of object exist, undo twice */
            if(shh.getNumberOfSimulatedHumanObject() > 0 && shh.getNumberOfVisitorObj() >0)
            {
                ui->inputSummaryBox->undo();
                ui->inputSummaryBox->undo();
            }
            else
            {
                ui->inputSummaryBox->undo();
            }

            /* Free all simulatedHuman object memory (if any) */
            shh.resetAll();

            /* Set to default */
            ui->humanDirLabel->setText("...");
            ui->humanDirLabel->setDisabled(true);
        }

        /* Handle addition of simulated human (resident) */
        if(arg1 > shh.getNumberOfSimulatedHumanObject())
        {
            /* Undo summary box if there is already 1 or more object created */
            if(shh.getNumberOfVisitorObj() >= 1 && shh.getNumberOfSimulatedHumanObject() >= 1)
            {
                ui->inputSummaryBox->undo();
                ui->inputSummaryBox->undo();
            }
            else if(shh.getNumberOfVisitorObj() >= 1 || shh.getNumberOfSimulatedHumanObject() >= 1)
                ui->inputSummaryBox->undo();

            /* Add remainding object */
            for(int i=shh.getNumberOfSimulatedHumanObject();i<arg1;i++)
            {
                /* Create first person */
                int randResidentOf = rand() % bh.getNoOfFloor() + 2;
                shh.createSimulatedHuman(randResidentOf);
                shh.populateSimulatedHuman(bh.getNoOfFloor(), true);

                update = true;
            }

            ui->humanDirLabel->setText("...");
            ui->humanDirLabel->setDisabled(true);
        }
        else if(arg1 < shh.getNumberOfSimulatedHumanObject()) /* Handle deletion of simulated human (resident) */
        {
            if(shh.getNumberOfVisitorObj() >= 1)
            {
                /* Undo summary box regardless of whether there are existing data or not */
                ui->inputSummaryBox->undo();
                ui->inputSummaryBox->undo();
            }
            else
            {
                ui->inputSummaryBox->undo();
            }
            /* Delete object from the back until arg1 */
            for(int i=shh.getNumberOfSimulatedHumanObject();i>arg1;i--)
            {
                /* true = resident */
                shh.removeLastData(true);
                update = true;
            }
        }
        else if(arg1 == shh.getNumberOfSimulatedHumanObject()) /* CPU Management */
        {
            update = false;
        }

        if(update)
        {
            updateSummary(true);
            updateSummary(false);
            ui->inputSummaryBox->verticalScrollBar()->setValue(ui->inputSummaryBox->verticalScrollBar()->maximum());

            update = false;
        }
    }
}

/* Handle human visitor spin box value changed */
void MainWindow::on_humanVisitorSpinBox_valueChanged(int arg1)
{
    /* Get previous human file name and previous human label enabled status */
    bool prevHumanLabelStatus = ui->humanDirLabel->isEnabled();
    QString prevFilename = ui->humanDirLabel->text();

    bool update = false;

    /* Only update when value is more than or equal to 0 */
    if(arg1 >= 0)
    {
        /* Undo and clear memory if previous data is loaded */
        if(prevHumanLabelStatus == true && prevFilename != "...")
        {
            /* Two types of object exist, undo twice */
            if(shh.getNumberOfSimulatedHumanObject() > 0 && shh.getNumberOfVisitorObj() >0)
            {
                ui->inputSummaryBox->undo();
                ui->inputSummaryBox->undo();
            }
            else
            {
                ui->inputSummaryBox->undo();
            }

            /* Free all simulatedHuman object memory (if any) */
            shh.resetAll();

            /* Set to default */
            ui->humanDirLabel->setText("...");
            ui->humanDirLabel->setDisabled(true);
        }

        /* Handle addition of simulated human (visitor) */
        if(arg1 > shh.getNumberOfVisitorObj())
        {
            /* Undo summary box if there is already 1 or more object created */
            if(shh.getNumberOfVisitorObj() >= 1)
                ui->inputSummaryBox->undo();

            /* Add remainding object */
            for(int i=shh.getNumberOfVisitorObj();i<arg1;i++)
            {
                /* Create first person */
                shh.createSimulatedHuman(0);
                shh.populateSimulatedHuman(bh.getNoOfFloor(), false);

                update = true;
            }
        }
        else if(arg1 < shh.getNumberOfVisitorObj()) /* Handle deletion of simulated human (visitor) */
        {
            /* Undo summary box regardless of whether there are existing data or not */
            ui->inputSummaryBox->undo();

            /* Delete object from the back until arg1 */
            for(int i=shh.getNumberOfVisitorObj();i>arg1;i--)
            {
                /* false = visitor */
                shh.removeLastData(false);
                update = true;
            }
        }
        else if(arg1 == shh.getNumberOfVisitorObj()) /* CPU Management */
        {
            update = false;
        }

        if(update)
        {
            updateSummary(false);
            ui->inputSummaryBox->verticalScrollBar()->setValue(ui->inputSummaryBox->verticalScrollBar()->maximum());
            update = false;
        }
    }
}

/* Handle reset button press */
void MainWindow::on_resetBtn_clicked()
{
    /* reset all data to default */
    ui->humanDirLabel->setDisabled(true);
    ui->inputSummaryBox->clear();
    ui->outputBox->clear();
    ui->buildingDirLabel->setText("...");
    ui->humanDirLabel->setText("...");
    ui->algoCombo->setCurrentIndex(0);
    ui->humanTotalSpinBox->setValue(0);
    ui->humanAvgSpinBox->setValue(0);
    ui->humanVisitorSpinBox->setValue(0);
    ui->saveResultBtn->setDisabled(true);
    ui->humanTotalSpinBox->setDisabled(true);
    ui->humanAvgSpinBox->setDisabled(true);
    ui->humanVisitorSpinBox->setDisabled(true);

    /* reset building/lift data */
    bh.resetAll();
    lh.resetAll();
    shh.resetAll();
}

/* Handle help button press */
void MainWindow::onActionHelp()
{
    /* Help message to describe XML data structure */
    QString message = "<b>E.g. of Simulated Human XML</b><br>"
                       "&lt;human&gt;<br>"
                            "&nbsp;&nbsp;&nbsp;&nbsp;&lt;person weight=\"60\" resident=\"4\"&gt;<br>"
                                "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;floor travel=\"4\"/&gt;<br>"
                                "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;floor travel=\"20\"/&gt;<br>"
                            "&nbsp;&nbsp;&nbsp;&nbsp;&lt;/person&gt;<br>"
                            "&nbsp;&nbsp;&nbsp;&nbsp;&lt;person weight=\"78\" resident=\"27\"&gt;<br>"
                                "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;floor travel=\"27\"/&gt;<br>"
                            "&nbsp;&nbsp;&nbsp;&nbsp;&lt;/person&gt;<br>"
                            "&nbsp;&nbsp;&nbsp;&nbsp;&lt;person weight=\"69\" resident=\"0\"&gt;<br>"
                                "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;floor travel=\"27\"/&gt;<br>"
                            "&nbsp;&nbsp;&nbsp;&nbsp;&lt;/person&gt;<br>"
                        "&lt;/human&gt;<br><br>"
                        "-Person 1<br>"
                        "Weighs 60kg, living at 4th floor.<br>"
                        "He usually travels to 4th floor and 20th floor.<br>"
                        "-Person 2<br>"
                        "Weighs 78kg, living at 27th floor.<br>"
                        "He usually travels to 27th floor.<br>"
                        "-Person 3<br>"
                        "Weighs 69kg, not a resident here.(resident=0)<br>"
                        "He usually travels to 27th floor.<br><br>"
                        "<b>E.g. of Building XML</b><br>"
                        "&lt;building floors=\"28\" metrePerFloor=\"3\" householdPerFloor=\"4\"&gt;<br>"
                            "&nbsp;&nbsp;&nbsp;&nbsp;&lt;lift maxWeight=\"400\" speed=\"1\"/&gt;<br>"
                            "&nbsp;&nbsp;&nbsp;&nbsp;&lt;lift maxWeight=\"340\" speed=\"1\"/&gt;<br>"
                        "&lt;/building&gt;<br><br>"
                        "Building is 28 stories high with 4 household per floor<br>"
                        "Each level is 3 metres apart. It has two lift<br>"
                        "-Lift 1<br>"
                        "Maximum weight of 400kg and travels 1 second per floor<br>"
                        "-Lift 2<br>"
                        "Maximum weight of 340kg and travels 1 second per floor<br>";

    /* Pop-up message box */
    QMessageBox::information(this,tr("Help"),message);
}

/* Handle run button press */
void MainWindow::on_runBtn_clicked()
{
    /* Input manually */
    if(!ui->humanDirLabel->isEnabled()
       && (ui->humanAvgSpinBox->value() == 0 || ui->humanTotalSpinBox->value() == 0 || ui->buildingDirLabel->text() == "..."))
    {

        QMessageBox::warning(this,tr("Form incomplete"),"Please fill in all necessary fields");

    } else if(ui->humanDirLabel->isEnabled() /* Input by files */
              && (ui->humanDirLabel->text() == "..." || ui->buildingDirLabel->text() == "..."))
    {

        QMessageBox::warning(this,tr("Form incomplete"),"Please fill in all necessary fields");

    }
    else /* All fields are set */
    {
        /* Output message */
        QString message = "Simulation completed in 1.3s<br>"
                        ".<br>"
                        "..<br>"
                        "...<br>"
                        "....<br>"
                        ".....<br>"
                        "......<br>"
                        ".......<br>"
                        "........<br>"
                        ".........<br>"
                        "..........<br>"
                        "...........<br>";

        /* Set output message */
        ui->outputBox->setText(message);
        ui->saveResultBtn->setDisabled(false);
    }
}

/* Handle save result button clicked */
void MainWindow::on_saveResultBtn_clicked()
{
    /* Initialize current date time */
    QDateTime local(QDateTime::currentDateTime());

    /* Display QFileDialog prompt */
    QString fileName = QFileDialog::getSaveFileName(
                this,
                tr("Save File"), "Result_"+local.toString("dMMM_HHmmap")+".txt",
                tr("Text Documents (*.txt);;"));


    /* Save and display success */
    if(!fileName.isEmpty())
        QMessageBox::information(this,tr("Help"),"File saved to "+fileName);
}

/* validate building XML */
QString MainWindow::validateBuildingData(const QString &arg1)
{
    /* header */
    QString header = "<b><font size=\"4\">Building Data</font></b><br>"
                          "====================<br>";

    /* Stores file data */
    QString summary;
    summary += header;

    /* load XML */
    TiXmlDocument doc(arg1.toStdString().c_str());

    /* Check if file can be open */
    if(doc.LoadFile())
    {
        TiXmlElement *pRoot, *pParm;

        /* checks if building exist */
        pRoot = doc.FirstChildElement("building");
        if(pRoot)
        {
            /* check if floors, metrePerFloor, householdPerFloor exist */
            if(pRoot->Attribute("floors") != NULL && pRoot->Attribute("metrePerFloor") != NULL && pRoot->Attribute("householdPerFloor") != NULL)
            {
                /* checks for floors, metrePerFloor, householdPerFloor is a number/empty data */
                int attr;
                if(TIXML_SUCCESS != pRoot->QueryIntAttribute("floors", &attr) || TIXML_SUCCESS != pRoot->QueryIntAttribute("metrePerFloor", &attr) || TIXML_SUCCESS != pRoot->QueryIntAttribute("householdPerFloor", &attr))
                    return "false";

                /* Floors must be at least 2 level */
                pRoot->QueryIntAttribute("floors", &attr);
                if(attr < 2)
                {
                    return "false";
                }
                else
                {
                    /* Append data to QString */
                    summary += "Total number of floors ";
                    summary += pRoot->Attribute("floors");
                    summary += "<br>";

                    /* set total number of floors */
                    bh.setNoOfFloors(attr);
                }

                /* metrePerFloor must be at least 3m*/
                pRoot->QueryIntAttribute("metrePerFloor", &attr);
                if(attr < 3)
                {
                    return "false";
                }
                else
                {
                    /* Append data to QString */
                    summary += "Number of metres per floor ";
                    summary += pRoot->Attribute("metrePerFloor");
                    summary += "<br>";

                    /* set metre per floor */
                    bh.setMetrePerFloor(attr);
                }

                /* householdPerFloor must be at least 1 or more*/
                pRoot->QueryIntAttribute("householdPerFloor", &attr);
                if(attr < 1)
                {
                    return "false";
                }
                else
                {
                    /* Append data to QString */
                    summary += "Number of household per floor ";
                    summary += pRoot->Attribute("householdPerFloor");
                    summary += "<br>";

                    /* set number of household per floor */
                    bh.setHouseholdPerFloor(attr);
                }

                /* check if first element of building exist */
                pParm = pRoot->FirstChildElement();
                if(pParm)
                {
                    int liftCount = 0;
                    while(pParm)
                    {
                        if(strcmp(pParm->Value(),"lift") == 0)
                        {
                            liftCount++;

                            /* check if maxWeight, speed exist */
                            if(pParm->Attribute("maxWeight") == NULL || pParm->Attribute("speed") == NULL)
                                return "false";
                            else
                            {
                                /* checks for maxWeight, speed is a number/empty data */
                                int attr2;
                                if(TIXML_SUCCESS != pParm->QueryIntAttribute("maxWeight", &attr2) || TIXML_SUCCESS != pParm->QueryIntAttribute("speed", &attr2))
                                    return "false";

                                int maxWeight, speed = 0;

                                /* maxWeight must be at least 200kg */
                                pParm->QueryIntAttribute("maxWeight", &attr2);
                                if(attr2 < 200)
                                {
                                    return "false";
                                }
                                else
                                {
                                    /* Append data to QString */
                                    summary += "<b>Lift no ";
                                    summary += QString::number(liftCount);
                                    summary += "</b><br>";
                                    summary += "Maximum weight ";
                                    summary += pParm->Attribute("maxWeight");
                                    summary += "kg<br>";

                                    maxWeight = attr2;
                                }

                                /* speed must be at least 1 or more*/
                                pParm->QueryIntAttribute("speed", &attr2);
                                if(attr2 < 1)
                                {
                                    return "false";
                                }
                                else
                                {
                                    /* Append data to QString */
                                    summary += "Maximum speed ";
                                    summary += pParm->Attribute("speed");
                                    summary += "sec/floor<br>";

                                    speed = attr2;
                                }

                                /* Create new lift object */
                                lh.createNewLift(liftCount, maxWeight, speed);

                                pParm = pParm->NextSiblingElement();
                            }
                        }
                        else
                        {
                            return "false";
                        }
                    }

                    /* set number of lifts */
                    bh.setNoOfLifts(liftCount);
                }
                else
                {
                    return "false";
                }
            }
            else
            {
                return "false";
            }
        }
        else
        {
            return "false";
        }
    }
    else
    {
        return "false";
    }

    lh.getAllLiftData();
    return summary;
}

/* validate human XML */
bool MainWindow::validateHumanData(const QString &arg1)
{
    /* Resident Status */
    bool isResident = true;

    /* Load XML */
    TiXmlDocument doc(arg1.toStdString().c_str());

    /* Check if file can be open */
    if(doc.LoadFile())
    {
        TiXmlElement *pRoot, *pParm, *pParm2;

        /* checks if human exist */
        pRoot = doc.FirstChildElement("human");
        if(pRoot)
        {
            /* Check if first element of human exist */
            pParm = pRoot->FirstChildElement();
            if(pParm)
            {
                while(pParm)
                {
                    /* is the element named "person" */
                    if(strcmp(pParm->Value(),"person") == 0)
                    {
                        /* checks if weight, resident exist */
                        if(pParm->Attribute("weight") != NULL && pParm->Attribute("resident") != NULL)
                        {
                            /* checks for weight, resident is a number/empty data */
                            int attr;
                            if(TIXML_SUCCESS != pParm->QueryIntAttribute("weight", &attr) || TIXML_SUCCESS != pParm->QueryIntAttribute("resident", &attr))
                                return false;

                            /* person must have a resident value of more than 0 but not 1 and less than building limit */
                            pParm->QueryIntAttribute("resident", &attr);
                            if((attr < 0) || (attr > bh.getNoOfFloor()) || attr == 1)
                            {
                                return false;
                            }
                            else
                            {
                                /* Check if is resident */
                                if(strcmp(pParm->Attribute("resident"),"0") == 0)
                                    isResident = false;
                                else
                                    isResident = true;

                                /* Create a simulatedHuman object with resident value*/
                                shh.createSimulatedHuman(attr);
                            }

                            /* person must have a weight of more than 0 and 150 or lower */
                            pParm->QueryIntAttribute("weight", &attr);
                            if(attr > 150 || attr < 1)
                            {
                                return false;
                            }
                            else
                            {
                                /* Set weight for simulatedHuman */
                                if(isResident)
                                    shh.setWeight(shh.getNumberOfSimulatedHumanObject(), attr, isResident);
                                else
                                    shh.setWeight(shh.getNumberOfVisitorObj(), attr, isResident);
                            }

                            /* checks if first element of person exist */
                            pParm2 = pParm->FirstChildElement();
                            if(pParm2)
                            {
                                while(pParm2)
                                {
                                     /* is the element named "floor" */
                                    if(strcmp(pParm2->Value(),"floor") == 0)
                                    {
                                        /* check if travel exist */
                                        if(pParm2->Attribute("travel") != NULL)
                                        {
                                            /* checks if travel is a number/empty data */
                                            int attr2;
                                            if(TIXML_SUCCESS != pParm2->QueryIntAttribute("travel", &attr2))
                                                return false;

                                            /* checks if person is travelling at least to level 2 or more
                                             * but lesser than the total limit in building */
                                            if(attr2 < 2 || attr2 > bh.getNoOfFloor())
                                            {
                                                return false;
                                            }
                                            else
                                            {
                                                if(isResident)
                                                    shh.addFloorTravelling(shh.getNumberOfSimulatedHumanObject(), attr2, isResident);
                                                else
                                                    shh.addFloorTravelling(shh.getNumberOfVisitorObj(), attr2, isResident);
                                            }

                                            pParm2 = pParm2->NextSiblingElement();
                                        }
                                        else
                                        {
                                            return false;
                                        }
                                    }
                                    else
                                    {
                                        return false;
                                    }
                                }
                                pParm = pParm->NextSiblingElement();
                            }
                            else
                            {
                                return false;
                            }
                        }
                        else
                        {
                            return false;
                        }
                    }
                    else
                    {
                        return false;
                    }
                }
            }
            else
            {
                return false;
            }
        }
        else
        {
            return false;
        }
    }
    else
    {
        return false;
    }

    shh.getAllPersonData();

    return true;
}

/* Update summary */
void MainWindow::updateSummary(bool isResident)
{
    /* Header */
    QString header;

    if(isResident)
    {
        /* Append header */
        if(shh.getNumberOfSimulatedHumanObject() >= 1 || shh.getNumberOfVisitorObj() >= 1)
        {
            header = "<b><font size=\"4\">Simulated Human Data</font></b><br>"
                     "====================<br>";

            if(shh.getNumberOfSimulatedHumanObject() >= 1)
            {
                /* Create text dynamically */
                for(int i=0;i<shh.getNumberOfSimulatedHumanObject();i++)
                {
                    /* Append data to QString */
                    header += "<b>Person number ";
                    header += QString::number(shh.getPersonID(i, true));

                    header += "</b><br>Is a resident staying at level ";
                    header +=  QString::number(shh.getResident(i, true));
                    header += "<br>";

                    /* Append data to QString */
                    header += "Weighs ";
                    header += QString::number(shh.getWeight(i, true));
                    header += "kg<br>";

                    /* Append data to QString */
                    header += "Will travel to floor ";

                    for(int j=0;j<shh.getFloorTravellingSize(i, true);j++)
                    {
                        /* Append data to QString */
                        header += QString::number(shh.getFloorTravelling(i, j, true));
                        header += ", ";
                    }

                    /* remove last comma */
                    header.remove(header.length()-2,1);

                    if(i != shh.getNumberOfSimulatedHumanObject()-1)
                    {
                        /* Append data to QString */
                        header += "<br>";
                    }
                }

                ui->inputSummaryBox->append(header);
            }
        }
    }
    else
    {
        /* If there are visitors, update */
        if(shh.getNumberOfVisitorObj() >= 1)
        {

            /* If there are no resident object, append header */
            if(shh.getNumberOfSimulatedHumanObject() <= 0)
            {
                header = "<b><font size=\"4\">Simulated Human Data</font></b><br>"
                         "====================<br>";
            }
            /* Create text dynamically */
            for(int i=0;i<shh.getNumberOfVisitorObj();i++)
            {
                /* Append data to QString */
                header += "<b>Visitor number ";
                header += QString::number(shh.getPersonID(i, false));
                header += "</b><br>Is not a resident<br>";

                /* Append data to QString */
                header += "Weighs ";
                header += QString::number(shh.getWeight(i, false));
                header += "kg<br>";

                /* Append data to QString */
                header += "Will travel to floor ";

                for(int j=0;j<shh.getFloorTravellingSize(i, false);j++)
                {
                    /* Append data to QString */
                    header += QString::number(shh.getFloorTravelling(i, j, false));
                    header += ", ";
                }

                /* remove last comma */
                header.remove(header.length()-2,1);

                /* Append data to QString */
                header += "<br>";
            }

            ui->inputSummaryBox->append(header);
        }
    }
}

/* FOR DEBUGGING PURPOSES ONLY */
/* Check current created object */
void MainWindow::onActionCheckObj()
{
    /* Message */
    QString message = "Number of lift object(s) = "
                    + QString::number(lh.getNumberOfLiftsObject())
                    + "<br>"
                    + "Number of simulatedHuman object(s) = "
                    + QString::number(shh.getNumberOfSimulatedHumanObject())
                    + "<br>"
                    + "Number of non resident object(s) = "
                    + QString::number(shh.getNumberOfVisitorObj());

    /* Pop-up message box */
    QMessageBox::information(this,tr("Number of objects"),message);
}
